spring.datasource.url=jdbc:mysql://localhost:3306/SmartWeldHub?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# eSewa test (sandbox)
esewa.merchant-code=EPAYTEST
esewa.secret-key=8gBm/:&EnhH.1/q

esewa.payment-url=https://rc-epay.esewa.com.np/api/epay/main/v2/form
esewa.status-url=https://rc-epay.esewa.com.np/api/epay/transaction/status
